### ISSUE TITLE
Not receiving - Ableton

### ISSUE THREAD

**Issue by caninereason** [cgfarmer4/TheConductor#1]
Hi was just wondering if you're using 32 or 64 bit. I can't seem to get ableton to pick up the input, despite oschelper.cs  saying values are being sent.. Any ideas or suggestions?

**Comment by cgfarmer4** [comment]
I use 64 bit. Are you using OSX or Windows? Windows I had a lot of trouble dealing with the firewall so I just turned it off. Which obviously isn't great but you should be able to add rules to it.

Otherwise just typical network debugging.

**Comment by caninereason** [comment]
On Win64 , must try some network debugging so, awesome work  btw. Thanks!

**Comment by cgfarmer4** [comment]
Some things to try ::
- Making sure IP addresses are pinging correctly if using separate machines. If not make sure localhost is sending / receiving.
- Checking ports are opened correctly for udp send / receive.
- Click the little Max for Live icon that opens Max and look in the console to see if you have any errors there.
- Adding a global OSC receive function to see if OSC is passing correctly.

Let me know how it goes.
