### ISSUE TITLE
Ableton is not sending any OSC message

### ISSUE THREAD

**Issue by YeonJunKim** [cgfarmer4/TheConductor#2]
Thanks for the quick reply on Youtube.
I'm pretty sure I followed your instructions very well,
but my Ableton is not sending any OSC message out.
How do I know this is that I downloaded OSC data monitoring program,
and tested both Unity and Ableton.
Unity sends OSC message well, it's captured on the monitoring program.
But no matter what parameter I give to Ableton, the message is not captured.
Like giving MidiEvents, MidiReceiveEvents different port, ip, pitch, velocity, name, or different Midi Output Device selection.
Also did with VRMidiKeyboard, VRDrumPads.

I did download CNMAT-odot-master and put it in the Max 8 Packages folder.
I've tested with other Ableton OSC sender, witch is Livegrabber,  and it sends out OSC well.
I've been struggling with this for almost a day now :(

Is there any suggestions?

**Comment by cgfarmer4** [comment]
Hi there -

I have moved on from VR development but am still active with Unity and Ableton. Apologies that you are struggling. Lets try to fix it together.

Can you tell me what's in your Max console?

![screen shot 2018-11-04 at 2 23 28 pm](https://user-images.githubusercontent.com/336449/47970645-3dd81b80-e03d-11e8-9c2c-89eb281244cc.png)

This is your debugging console similar to Unity. You can tap into each of the functions in Max to see if the OSC is even working at all. 

I will try sometime next week to get back into this project and port it to a more standardized Raycast interaction vs VR controls.

-Chase

**Comment by YeonJunKim** [comment]
Hi there

I'm sorry I got back to you so late
I was working so busy on my project

Here is the debugging console 

![asdasdsads](https://user-images.githubusercontent.com/41028564/48312430-ba489c80-e5f1-11e8-84cf-b6de134c6386.PNG)


And this is my OSC_Data_Monitor to see any OSC packets flying on my computer
Apparently none

![adad](https://user-images.githubusercontent.com/41028564/48312445-f7ad2a00-e5f1-11e8-8120-32338865acac.PNG)

**Comment by cgfarmer4** [comment]
All of those red error messages are the fact that Max isn't finding o.dot. 

Can you confirm its in the Max 8 packages folder?

**Comment by YeonJunKim** [comment]
I checked my Max 8 packages folder. 'CNMAT-odot-master' folder was in there.
This is the path to o-dot.
"C:\Users\remn0\OneDrive\문서\Max 8\Packages\CNMAT-odot-master"  
(the actual path that is in Korean, because my computer is Korean)

"C:\Users\remn0\OneDrive\Documents\Max 8\Packages\CNMAT-odot-master" 
(English version of the path,   '문서' = 'Documents')

I'm pretty sure that, that is the right place.

I thought if it was the o-dot folder that was broken, so I downloaded o-dot again from 
"https://github.com/CNMAT/CNMAT-odot" here.

And placed it in the Max 8 packages folder. But still the same error occurs on Max Console.

I am running this on Ableton 10 Live (trial version), and Max 8.

**Comment by cgfarmer4** [comment]
Hi there-

Yes the problem is that you aren't using the Windows build of Odot. I should have detailed this better in the docs that there were separate builds per OS. Download the link below and replace current odot folder.

https://github.com/CNMAT/CNMAT-odot/releases/download/v1.2-20_beta/odot-Max-Win32-64-v1.2-20_beta.zip

**Comment by YeonJunKim** [comment]
Hi
I've got some good news!
I downloaded Windows Build of Odot that you linked, and put it in the Max 8 packages folder, and it worked!!
It works very well.

Thanks for the help.

**Comment by cgfarmer4** [comment]
Great! I will update the readme to better reflect where to get the correct build.
